name: mini_game_via_flame
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.15.0
  flame_audio: ^2.1.8
  flame_bloc: ^1.10.10
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  flame_noise: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/Archer/Character/
    - assets/images/Archer/Arrow/
    - assets/images/Sword Man/
    - assets/images/Enemies/Flying eye/
    - assets/images/Enemies/Goblin/
    - assets/images/Enemies/Mushroom/
    - assets/images/Enemies/Skeleton/
    - assets/audio/

  fonts:
    - family: vinque
      fonts:
        - asset: assets/fonts/VINQUE.OTF
